### ISSUE TITLE
Preset text missing in puirty.

### ISSUE THREAD

**Issue by TheGuyWhoo** [robbert-vdh/yabridge#278]
### Thanks for giving yabridge a shot!

- [X] I read through both the troubleshooting and the known issues sections, and my issue wasn't listed there

### Problem description

The text in Purity by SonicCat doesn't show, despite having all fonts installed. 

### What did you expect to happen?

Be able to see text in preset window.

### What actually happened?

 Preset text(as in the name of the preset in the preset window) isn't displayed. All other text seem to show up.

### Operating system

linux mint 20

### How did you install yabridge?

directly from releases

### yabridge version

latest

### yabridgectl version

latest

### Wine version

staging 7.9

### Plugin

Purity

### Plugin type

VST2

### Plugin architecture

64-bit

### Host

Reaper 6.79

### Desktop environment or WM

xorg

**Comment by robbert-vdh** [comment]
You're likely still missing some fonts. If installing `corefonts` and `allfonts` through winetricks doesn't do the trick then figuring out which font is used can be a bit tricky as that involves tracing Wine's (off by default) font loading debug messages.

Closing since this is not an issue with yabridge itself.

**Comment by TheGuyWhoo** [comment]
nvm, I fixed it somehow. It seems something was wrong somewhere outside of drive_c, because I delete the symlink to it then deleted the wine prefix and let it regenerate. Then I relinked my drive_c and the issue fixed itself.

**Comment by QXR9** [comment]
> nvm, I fixed it somehow. It seems something was wrong somewhere outside of drive_c, because I deleted the symlink to it then deleted the wine prefix and let it regenerate. Then I relinked my drive_c and the issue fixed itself.

Can you explain how can I do that? I installed fonts but I still have the same problem.
